import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import socketClient from 'socket.io-client'
export default function Home() {
  var socket = socketClient('http://localhost:8080')
  socket.on('msg', msg=>{
    console.log(msg)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Pingador V4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container`}>
        <Navbar />

      </main>
    </div>
  )
}
